### ISSUE TITLE
System commands

### ISSUE THREAD

**Issue by zaro0508** [Sage-Bionetworks/jccli#23]
Port all "System Functions" from the JC powershell command reference, https://github.com/TheJumpCloud/support/wiki/Set-JCSystem

**Comment by cascadianblue** [comment]
How do we run integration tests for this one? My impression is that the only way to add a system is to actually add a system

**Comment by zaro0508** [comment]
you probably won't be able to do integration tests for this unless you integrate an cloud account into your tests.

**Comment by cascadianblue** [comment]
This is resolved except for the work described in #89 .
