### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by zaro0508** [Sage-Bionetworks/jccli#24]
This project is lacking unit tests.  We need some ASAP

**Comment by cascadianblue** [comment]
I see lots of unit tests in the tests/ directory. They do run on pytest, so you might not be detecting them if you are running Python's built-in unittest library

**Comment by cascadianblue** [comment]
Granted, test coverage is probably insufficient. There are no CLI tests for the "sync" command. I might work on that
